[application]
# role: identifier for WindowManager (used in layers.json)
# e.g. role = "WebBrowser"
role = "Spotify"

# launch by "POSIX"(fork/exec), "AFM_DBUS"(afm via dbus),  "AFM_WEBSOCKET"(afm via websockt)
method = "POSIX"

# path: path to the executable
# e.g.
path = "/usr/bin/web-runtime"

# params: arguments of the excecutable 
# e.g.
   params = [
     "http://localhost:@port@/index.html?token=@token@"
   ]

