#!/bin/bash

# Copyright (C) 2018-2019 
#		Stephane Desneux <stephane.desneux@iot.bzh>
#		Ronan Le Martret <ronan.lemartret@iot.bzh>
# Released under the Apache 2.0 license

BASEDIR=/usr/share/platform-test

function info() { echo "$@" >&2; }

if [[ $# -gt 0 ]]; then
	case $1 in
		-d|--detect)
			info "Running hardware detection" 
			systemctl start platform-core-detection.service
			systemctl start platform-devices-detection.service
			;;
		-h|--help|*)
			info "$0 [-h|--help] [-d|--detect]"
			exit 1
			;;
	esac 
fi

# source hw definitions
. /etc/platform-info/core
. /etc/platform-info/devices

cd $BASEDIR

[[ ! -f platform-test_${HW_BOARD_MODEL} ]] && {
	info "platform-test: Unknown board model"
	exit 1
}

exec bash -e platform-test_${HW_BOARD_MODEL}
