#!/bin/bash

# Copyright (C) 2018-2019 
#		Stephane Desneux <stephane.desneux@iot.bzh>
#		Ronan Le Martret <ronan.lemartret@iot.bzh>
# Released under the Apache 2.0 license

for t in Ethernet HDMI USB; do
	script=tests/test-$t
	bash -e $script || echo "FAIL: invalid test script $script"
done

