#!/bin/bash

# Copyright (C) 2018-2019 
#		Stephane Desneux <stephane.desneux@iot.bzh>
#		Ronan Le Martret <ronan.lemartret@iot.bzh>
# Released under the Apache 2.0 license

set -e

MYNAME=$(basename $BASH_SOURCE)

confdir_default=$(cd $(dirname $(realpath $BASH_SOURCE)) && pwd -P)

function info() { echo "$(basename $BASH_SOURCE) - $@" >&2; }
function warning() { echo "$(basename $BASH_SOURCE) - WARNING: $@" >&2; }
function error() { echo "$(basename $BASH_SOURCE) - ERROR: $@" >&2; }

DEVINFO=/etc/platform-info/devices

[[ ! -f $DEVINFO ]] && { error "Unable to find $DEVINFO"; exit 1; }

. $DEVINFO || { error "Unable to source $DEVINFO"; exit 2; }
 
# --------------------------------------------------------------

[[ -d ${confdir_default}/COMMON ]] && {
    for sc in $(ls ${confdir_default}/COMMON);do
        bash $dir/$sc
    done
}

for key in BLUETOOTH_DEVICES ETHERNET_DEVICES CAN_DEVICES WIFI_DEVICES; do
	hwkey="HW_$key"
	[[ -d ${confdir_default}/$key ]] && 
	[[ -n "${!hwkey}" ]] && {
		for sc in $(ls ${confdir_default}/COMMON);do
			bash $dir/$sc ${!hwkey}
		done
	}
done

