#!/bin/bash

# Copyright (C) 2018-2019 
#		Stephane Desneux <stephane.desneux@iot.bzh>
#		Ronan Le Martret <ronan.lemartret@iot.bzh>
# Released under the Apache 2.0 license

SCRIPT_DIR=$( cd "$( dirname "$0" )" && pwd )
. ${SCRIPT_DIR}/common.sh

TEST_MSG="Radio device detection"

RADIO_DEV=$(arecord -l | grep "radio")

if [ "${RADIO_DEV}" ]
then
	pass ${TEST_MSG}
else
	fail ${TEST_MSG}
fi
