#!/bin/bash

# Copyright (C) 2018-2019 
#		Stephane Desneux <stephane.desneux@iot.bzh>
#		Ronan Le Martret <ronan.lemartret@iot.bzh>
# Released under the Apache 2.0 license

SCRIPT_DIR=$( cd "$( dirname "$0" )" && pwd )
. ${SCRIPT_DIR}/common.sh

TEST_MSG="USB bus detection"

case $HW_BOARD_MODEL in 
	kingfisher-?3ulcb-*)
		USB_DEVICES="1 2"
		;;
	?3ulcb-*)
		USB_DEVICES="1"
		;;
	*)
		USB_DEVICES="1"
		;;
esac

for dev in $USB_DEVICES
do
	RET=$(lsusb -s ${dev}:)
	if [ "${RET}" ]
	then
		pass ${TEST_MSG} $dev
	else
		fail ${TEST_MSG} $dev
	fi
done
