#!/bin/bash

# Copyright (C) 2018-2019 
#		Stephane Desneux <stephane.desneux@iot.bzh>
#		Ronan Le Martret <ronan.lemartret@iot.bzh>
# Released under the Apache 2.0 license

SCRIPT_DIR=$( cd "$( dirname "$0" )" && pwd )
. ${SCRIPT_DIR}/common.sh

TEST_MSG="Ethernet device detection"

for dev in ${HW_ETHERNET_DEVICES}
do
	ip link show dev ${dev} &> /dev/null
	[ $? -eq 0 ] && pass ${TEST_MSG} $dev || fail ${TEST_MSG} $dev
done
