#!/bin/bash

# Copyright (C) 2018-2019 
#		Stephane Desneux <stephane.desneux@iot.bzh>
#		Ronan Le Martret <ronan.lemartret@iot.bzh>
# Released under the Apache 2.0 license

set -e

MYNAME=$(basename $BASH_SOURCE)

confdir_default=$(cd $(dirname $(realpath $BASH_SOURCE)) && pwd -P)

function info() { echo "$(basename $BASH_SOURCE) - $@" >&2; }
function warning() { echo "$(basename $BASH_SOURCE) - WARNING: $@" >&2; }
function error() { echo "$(basename $BASH_SOURCE) - ERROR: $@" >&2; }

HWINFO=/etc/platform-info/hardware

[[ ! -f $HWINFO ]] && { error "Unable to find $HWINFO"; exit 1; }

. $HWINFO || { error "Unable to source $HWINFO"; exit 2; }
 
# --------------------------------------------------------------

LISTDIR="${confdir_default}/COMMON"

for key in CPU_ARCH SOC_VENDOR BOARD_MODEL; do
	hwkey="HW_$key"
	[[ -z "${!hwkey}" ]] && { warning "$hwkey is not set - please check $HWINFO"; continue; }
	LISTDIR="${LISTDIR} ${confdir_default}/$key/${!hwkey}"
done

for dir in $LISTDIR; do
	[[ -d $dir ]] && {
		for sc in $(ls $dir);do
			bash $dir/$sc
		done
	}
done
