#!/bin/bash

# Copyright (C) 2018-2019 
#		Stephane Desneux <stephane.desneux@iot.bzh>
#		Ronan Le Martret <ronan.lemartret@iot.bzh>
# Released under the Apache 2.0 license

set -e

MYNAME=$(basename $BASH_SOURCE)

confdir_default=$(cd $(dirname $(realpath $BASH_SOURCE)) && pwd -P)

function info() { echo "$(basename $BASH_SOURCE) - $@" >&2; }
function warning() { echo "$(basename $BASH_SOURCE) - WARNING: $@" >&2; }
function error() { echo "$(basename $BASH_SOURCE) - ERROR: $@" >&2; }

function run_script() {
	local sc=$1; shift
	info "Running: $sc $@"
	bash $sc "$@"|| error "script $sc FAILED with $?"
	return 0
}

DEVINFO=/etc/platform-info/devices

[[ ! -f $DEVINFO ]] && { error "Unable to find $DEVINFO"; exit 1; }

. $DEVINFO || { error "Unable to source $DEVINFO"; exit 2; }
 
# --------------------------------------------------------------

# run all scripts in 'common'
[[ -d ${confdir_default}/common ]] && {
	for sc in $(ls ${confdir_default}/common);do
		run_script $dir/$sc
	done
}

# keys are defined in /etc/platform-info/devices
CATEGORIES="\
   BLUETOOTH_DEVICES \
   ETHERNET_DEVICES \
   CAN_DEVICES \
   WIFI_DEVICES \
"
for key in $CATEGORIES; do
	hwkey="HW_$key"
	dirname=${key,,} # lowercase
	if [[ -d ${confdir_default}/$key && -n "${!hwkey}" ]]; then
		for sc in $(ls ${confdir_default}/$dirname);do
			run_script $dir/$sc ${!hwkey}
		done
	fi
done

